<?php
/**
 * Plugin Name: ZeroPlastic REST origin
 * Description: Serves the WordPress REST API from the CMS hostname while the public site is served by Cloudflare. Does nothing else.
 * Version:     1.0.0
 * Author:      ZeroPlastic Movement
 *
 * WP_HOME is the public site, www.zeroplastic.lk, which after cutover is
 * Cloudflare Pages and runs no WordPress at all.
 * WP_SITEURL is cms.zeroplastic.lk, where WordPress actually runs.
 *
 * get_rest_url() builds its URL from get_home_url(), not get_site_url()
 * (wp-includes/rest-api.php). Left alone, WordPress would therefore advertise
 * its REST root on the public host, which serves no /wp-json. The block editor
 * reads exactly that value for wp.apiFetch, so opening or saving a post would
 * fail: a 404, cross-origin, with no CORS headers.
 *
 * This filter moves only the REST API onto the CMS host. It deliberately does
 * not touch permalinks, feeds, canonical URLs or anything else generated from
 * home_url(), so public URLs stay on www.zeroplastic.lk.
 */

defined( 'ABSPATH' ) || exit;

add_filter(
	'rest_url',
	/**
	 * Swap the public origin for the CMS origin, and only that.
	 *
	 * Rewrites the origin prefix rather than doing a substring replace across
	 * the whole string, so a path or query that happens to contain the public
	 * hostname is left intact.
	 *
	 * Assumes both constants use the same scheme (https). If they ever differ,
	 * the prefix will not match and the URL is returned untouched, which fails
	 * safe rather than producing a malformed URL.
	 *
	 * @param string $url REST URL generated by WordPress.
	 * @return string
	 */
	static function ( $url ) {
		if ( ! is_string( $url ) || ! defined( 'WP_HOME' ) || ! defined( 'WP_SITEURL' ) ) {
			return $url;
		}

		$public = untrailingslashit( WP_HOME );
		$cms    = untrailingslashit( WP_SITEURL );

		if ( '' === $public || $public === $cms ) {
			return $url;
		}

		if ( 0 !== strpos( $url, $public ) ) {
			return $url;
		}

		return $cms . substr( $url, strlen( $public ) );
	},
	10,
	1
);
